Repository edgexfoundry/edgex-docs, pull requests merged in 2020-08, with the labels that each got.

#163 Documentation of How To Guide on SSH Tunneling of remote device services
  docs_src/microservices/security/Ch-SSH-Tunneling-HowToSecureDeviceServices.md
  docs_src/microservices/security/ssh-tunneling_device.png
Labels: device-services, documentation, enhancement, hanoi, hold, request for comments, security-services

#199 update the microservice support logging page - marking the service as…
  docs_src/microservices/support/logging/Ch-Logging.md
  docs_src/microservices/support/logging/EdgeX_SupportingServicesLoggingArchitecture.png
Labels: documentation, geneva

#141 chore: ADR for creation and distribution of secrets
  docs_src/design/TOC.md
  docs_src/design/adr/security/0008-Secret-Creation-and-Distribution.md
Labels: hanoi

#212 updates to several of the example pages under Examples and Tutorials
  docs_src/examples/APIinquiry.png
  docs_src/examples/Ch-ExamplesModbusdatatypeconversion.md
  docs_src/examples/Ch-ExamplesProvisionDevice.md
  docs_src/examples/Ch-ExamplesRandomDeviceService.md
  docs_src/examples/Ch-ExamplesVirtualDeviceService.md
  docs_src/examples/RandomDeviceService-getcommand.png
  docs_src/examples/RandomDeviceService-putcommand.png
  docs_src/examples/Validate.png
  mkdocs.yml
Labels: documentation, geneva

#221 feat(sdk): HOW-TO enable remote device-service service via overlay ne…
  docs_src/microservices/security/Ch-Docker-Swarm-SecuringDeviceServices.md
  docs_src/microservices/security/overlay-network.png
Labels: documentation, hanoi, security-services

#224 fix #223; update the ADR on config and core config service pages to f…
  docs_src/design/adr/0005-Service-Self-Config.md
  docs_src/microservices/configuration/Ch-Configuration.md
Labels: bug, documentation, geneva

#226 docs: addition of version and LTS refs to getting started pages per a…
  docs_src/getting-started/Ch-GettingStartedDevelopers.md
  docs_src/getting-started/index.md
Labels: documentation, geneva
