Repository edgexfoundry/edgex-docs, pull requests merged in 2020-05, with the labels that each got.

#129 docs: restructure and update Application Services Docs a bit
  docs_src/examples/AppServiceExamples.md
  docs_src/getting-started/ApplicationFunctionsSDK.md
  docs_src/getting-started/index.md
  docs_src/microservices/application/AppServiceConfigurable.md
  docs_src/microservices/application/ApplServices.md
  docs_src/microservices/application/ApplicationFunctionsSDK.md
  docs_src/microservices/application/ApplicationServices.md
  docs_src/microservices/application/Ch-ApplicationFunctionsSDK.md
  docs_src/microservices/application/Ch-HTTPTrigger.md
  docs_src/microservices/application/Ch-MessageBusTrigger.md
  docs_src/microservices/application/Triggers.md
  mkdocs.yml
Labels: app-services, documentation, geneva

#122 Remove StringArray type. Note data transform ops will not be applied.
  docs_src/design/adr/device-service/0002-Array-Datatypes.md
Labels: documentation, geneva

#125 Update core/support config docs for Geneva release
  docs_src/microservices/configuration/Ch-Configuration.md
  docs_src/microservices/core/data/Ch-CoreData.md
  docs_src/microservices/core/metadata/Ch-Metadata.md
  docs_src/microservices/support/logging/Ch-Logging.md
  docs_src/microservices/support/notifications/Ch-AlertsNotifications.md
  docs_src/microservices/support/rulesengine/Ch-RulesEngine.md
  docs_src/microservices/support/scheduler/Ch-Scheduling.md
Labels: 2-medium, documentation, enhancement, geneva
