Repository edgexfoundry/edgex-docs, pull requests merged in 2020-06, with the labels that each got.

#139 docs: add device profile information
  docs_src/microservices/device/profile/Ch-DeviceProfile.md
  docs_src/microservices/device/profile/Ch-DeviceProfileRef.md
  docs_src/microservices/device/profile/EdgeX_DeviceProfile.png
Labels: device-services, documentation, geneva

#145 fix #142 - add deprecation warning to logging service
  docs_src/microservices/support/Kuiper/Ch-Kuiper.md
  docs_src/microservices/support/Kuiper/arch.png
  docs_src/microservices/support/Kuiper/arch_light.png
  docs_src/microservices/support/logging/Ch-Logging.md
  docs_src/microservices/support/rulesengine/Ch-RulesEngine.md
  mkdocs.yml
Labels: documentation, geneva

#173 fixes #24; clean up of getting started page and added getting started…
  docs_src/getting-started/Ch-GettingStartedSnapUsers.md
  docs_src/getting-started/Ch-GettingStartedUsers.md
  docs_src/getting-started/index.md
  mkdocs.yml
Labels: documentation
