Repository edgexfoundry/edgex-docs, pull requests merged in 2020-09, with the labels that each got.

#192 Update the getting started device service sdk pages
  docs_src/general/Definitions.md
  docs_src/getting-started/Ch-GettingStartedCDevelopers.md
  docs_src/getting-started/Ch-GettingStartedSDK-C.md
  docs_src/getting-started/Ch-GettingStartedSDK-Go.md
  docs_src/getting-started/Ch-GettingStartedSDK.md
  docs_src/getting-started/EdgeX_DeviceServiceSDK.png
  docs_src/getting-started/EdgeX_GettingStartedGoModInit.png
  docs_src/getting-started/EdgeX_GettingStartedLocateDriver.png
  docs_src/getting-started/EdgeX_GettingStartedSDKBuild.png
  docs_src/getting-started/EdgeX_GettingStartedSDKBuild1.png
  docs_src/getting-started/EdgeX_GettingStartedSDKBuild2.png
  docs_src/getting-started/EdgeX_GettingStartedSDKClone.png
  docs_src/getting-started/EdgeX_GettingStartedSDKClone1.png
  docs_src/getting-started/EdgeX_GettingStartedSDKClone2.png
  docs_src/getting-started/EdgeX_GettingStartedSDKClone3.png
  docs_src/getting-started/EdgeX_GettingStartedSDKClone4.png
  docs_src/getting-started/EdgeX_GettingStartedSDKClone5.png
  docs_src/getting-started/EdgeX_GettingStartedSDKClone6.png
  docs_src/getting-started/EdgeX_GettingStartedSDKClone7.png
  docs_src/getting-started/EdgeX_GettingStartedSDKCloneC.png
  docs_src/getting-started/EdgeX_GettingStartedSDKCode1.png
  docs_src/getting-started/EdgeX_GettingStartedSDKCode2.png
  docs_src/getting-started/EdgeX_GettingStartedSDKCode3.png
  docs_src/getting-started/EdgeX_GettingStartedSDKCode4.png
  docs_src/getting-started/EdgeX_GettingStartedSDKCompileC.png
  docs_src/getting-started/EdgeX_GettingStartedSDKCopyFiles.png
  docs_src/getting-started/EdgeX_GettingStartedSDKCopyFilesC.png
  docs_src/getting-started/EdgeX_GettingStartedSDKGoAddImports.png
  docs_src/getting-started/EdgeX_GettingStartedSDKGoGenNumber.png
  docs_src/getting-started/EdgeX_GettingStartedSDKGoMod.png
  docs_src/getting-started/EdgeX_GettingStartedSDKProject1.png
  docs_src/getting-started/EdgeX_GettingStartedSDKProject2.png
  docs_src/getting-started/EdgeX_GettingStartedSDKProject3.png
  docs_src/getting-started/EdgeX_GettingStartedSDKProject4.png
  docs_src/getting-started/EdgeX_GettingStartedSDKProject5.png
  docs_src/getting-started/EdgeX_GettingStartedSDKProject6.png
  docs_src/getting-started/EdgeX_GettingStartedSDKProject7.png
  docs_src/getting-started/EdgeX_GettingStartedSDKRebuild1.png
  docs_src/getting-started/EdgeX_GettingStartedSDKReplaceImports.png
  docs_src/getting-started/EdgeX_GettingStartedSDKRun1.png
  docs_src/getting-started/EdgeX_GettingStartedSDKRun2.png
  docs_src/getting-started/EdgeX_GettingStartedSDKRun3.png
  docs_src/getting-started/EdgeX_SampleDeviceProfile_DeviceResources.png
  docs_src/getting-started/EdgeX_SampleDeviceProfile_DeviceResourcesC.png
  docs_src/getting-started/configuration.toml
  docs_src/getting-started/random-generator-device.yaml
Labels: documentation, geneva

#233 fix: Fix links from App Service Config functions to SDK details for the functions
  docs_src/microservices/application/AppServiceConfigurable.md
Labels: geneva

#236 build: upgrade docs to reference use of Go 1.15
  docs_src/getting-started/Ch-GettingStartedGoDevelopers.md
Labels: documentation, enhancement, hanoi

#207 update the microservice system management page
  docs_src/microservices/system-management/Ch_CentralManagementSystem.png
  docs_src/microservices/system-management/Ch_SystemManagement.md
  docs_src/microservices/system-management/Ch_SystemManagement_Facilitates_Central.png
  docs_src/microservices/system-management/EdgeX_SysMgmtArch.png
  docs_src/microservices/system-management/EdgeX_SystemManagement.png
  docs_src/microservices/system-management/agent/Ch_SysMgmtAgent.md
  docs_src/microservices/system-management/executor/Ch_SysMgmtExecutor.md
  docs_src/microservices/system-management/executor/EdgeX-SME-Docker-in-Docker.png
  mkdocs.yml
Labels: documentation, geneva

#204 doc: Add (legacy) requirements document for Device SDKs (#190)
  docs_src/design/legacy-requirements/README.md
  docs_src/design/legacy-requirements/device-service.md
Labels: ADR

#196 Update microservices core command
  docs_src/general/Definitions.md
  docs_src/getting-started/Ch-GettingStartedSDK-C.md
  docs_src/microservices/core/command/Ch-Command.md
Labels: documentation, geneva

#237 docs(support): update supporting services main page
  docs_src/microservices/support/Ch-SupportingServices.md
  docs_src/microservices/support/EdgeX_SupportingServices.png
  docs_src/microservices/support/EdgeX_SupportingServicesHighlighted.png
  docs_src/microservices/support/EdgeX_SupportingServicesLayer.png
Labels: documentation, enhancement, geneva

#242 docs(examples): add Jonas Werner Tutorial to examples and tutorials
  docs_src/examples/LinuxTutorial/EdgeX-Foundry-tutorial-ver1.0.pdf
  docs_src/examples/LinuxTutorial/LinuxTutorial.md
  mkdocs.yml
Labels: documentation, enhancement, geneva

#214 update the API Walkthrough pages
  docs_src/walk-through/Ch-Walkthrough.md
  docs_src/walk-through/Ch-WalkthroughCommands.md
  docs_src/walk-through/Ch-WalkthroughData.md
  docs_src/walk-through/Ch-WalkthroughDeviceProfile.md
  docs_src/walk-through/Ch-WalkthroughDeviceService.md
  docs_src/walk-through/Ch-WalkthroughExporting.md
  docs_src/walk-through/Ch-WalkthroughProvision.md
  docs_src/walk-through/Ch-WalkthroughReading.md
  docs_src/walk-through/Ch-WalkthroughRunning.md
  docs_src/walk-through/Ch-WalkthroughSetup.md
  docs_src/walk-through/Ch-WalkthroughUseCase.md
  docs_src/walk-through/EdgeX_CameraMonitorProfile.yml
  docs_src/walk-through/EdgeX_WalkthroughAppServiceLog.png
  docs_src/walk-through/EdgeX_WalkthroughConsulKeyValue.png
  docs_src/walk-through/EdgeX_WalkthroughConsulSetLogLevel.png
  docs_src/walk-through/EdgeX_WalkthroughDockerProcesses.png
  docs_src/walk-through/EdgeX_WalkthroughExportServiceResponse.png
  docs_src/walk-through/EdgeX_WalkthroughGetCommands.png
  docs_src/walk-through/EdgeX_WalkthroughGetValueDescriptors.png
  docs_src/walk-through/EdgeX_WalkthroughLoggingRequest.png
  docs_src/walk-through/EdgeX_WalkthroughPostValueDescriptor.png
  docs_src/walk-through/EdgeX_WalkthroughPostmanFile.png
  docs_src/walk-through/EdgeX_WalkthroughPostmanPOST.png
  docs_src/walk-through/EdgeX_WalkthroughPutCommandURL.png
  docs_src/walk-through/EdgeX_WalkthroughSendEvent.png
  mkdocs.yml
Labels: documentation, geneva

#244 docs(reference): put all reference docs under a single tab
  docs_src/general/ContainerNames.md
  docs_src/general/Definitions.md
  docs_src/general/PlatformRequirements.md
  docs_src/general/ServiceConfiguration.md
  docs_src/general/ServicePorts.md
  docs_src/getting-started/quick-start/index.md
  docs_src/microservices/core/command/Ch-Command.md
  docs_src/microservices/core/data/Ch-CoreData.md
  docs_src/microservices/core/metadata/Ch-Metadata.md
  docs_src/microservices/device/Ch-DeviceServices.md
  docs_src/microservices/device/virtual/Ch-VirtualDevice.md
  docs_src/microservices/support/notifications/Ch-AlertsNotifications.md
  docs_src/microservices/support/scheduler/Ch-Scheduling.md
  docs_src/microservices/system-management/agent/Ch_SysMgmtAgent.md
  mkdocs.yml
Labels: documentation, enhancement, geneva
