Repository edgexfoundry/edgex-docs, pull requests merged in 2020-10, with the labels that each got.

#252 build: add Hanoi version 1.3
  mkdocs.yml
  versions.json
Labels: 2-medium, hanoi

#231 feat: Document Application Service's new AddTags function
  docs_src/microservices/application/AppServiceConfigurable.md
  docs_src/microservices/application/BuiltIn.md
Labels: hanoi

#245 docs(app-sdk): Expose RegistryClient
  docs_src/microservices/application/AdvancedTopics.md
Labels: hanoi

#229 docs(app-sdk): Add background publisher API detail
  docs_src/microservices/application/AdvancedTopics.md
Labels: hanoi

#240 docs(AppServices): Document the App Services new MQTT Trigger capability
  docs_src/microservices/application/GeneralAppServiceConfig.md
  docs_src/microservices/application/Triggers.md
Labels: hanoi

#256 build: add supporting files for conventional commits
  .github/Contributing.md
  .github/PULL_REQUEST_TEMPLATE.md
  .github/semantic.yml
Labels: ci, hanoi

#243 ci(adr): Hanoi updates to ADR for github releases and snaps
  docs_src/design/adr/devops/0007-Release-Automation.md
  docs_src/design/adr/devops/0007/appdevservices_mergeactions.png
  docs_src/design/adr/devops/0007/coreservices_mergeactions.png
  docs_src/design/adr/devops/0007/mergeactions.png
  docs_src/design/adr/devops/0007/releaseactions.png
  docs_src/design/adr/devops/0010-Release-Artifacts.md
  docs_src/design/adr/devops/0010/known-build-dependencies.png
Labels: hanoi

#261 feat(microservices): addition of cross cutting concern documentation
  docs_src/microservices/general/MultipleInstances.png
  docs_src/microservices/general/index.md
  mkdocs.yml
Labels: documentation, hanoi

#264 fix: replace broken link in pull request template
  .github/PULL_REQUEST_TEMPLATE.md
Labels: bug, documentation, hanoi

#217 feat: Proposal for new edgex-secrets-config utility.
  docs_src/microservices/security/edgex-secrets-config-proxy.1.md
  docs_src/microservices/security/edgex-secrets-config.1.md
Labels: documentation, hanoi

#220 feat(adr): Docker container guidelines
  docs_src/design/adr/system-management/001-docker-image-guidelines.md
Labels: ADR

#273 fix(ref): change default startup duration to 60 seconds
  docs_src/microservices/application/AdvancedTopics.md
  docs_src/microservices/configuration/Ch-Configuration.md
Labels: documentation, hanoi

#272 fix(microservices): remove RAML references/links from micro service p…
  docs_src/api/Ch-APISystemManagement.md
  docs_src/api/core/Ch-APICoreCommand.md
  docs_src/api/core/Ch-APICoreData.md
  docs_src/api/core/Ch-APICoreMetadata.md
  docs_src/api/supporting/Ch-APISupportingServicesAlerts.md
  docs_src/api/supporting/Ch-APISupportingServicesLogging.md
  docs_src/api/supporting/Ch-APISupportingServicesScheduling.md
  docs_src/examples/Ch-ExamplesAddingSNMPDevice.md
Labels: documentation, hanoi
