Repository edgexfoundry/edgex-docs, pull requests merged in 2020-07, with the labels that each got.

#178 Fixes #38; update and clean up of the Getting Started Developers page…
  docs_src/general/Definitions.md
  docs_src/getting-started/Ch-GettingStartedCDevelopers.md
  docs_src/getting-started/Ch-GettingStartedDevelopers.md
  docs_src/getting-started/Ch-GettingStartedGoDevelopers.md
  docs_src/getting-started/EdgeX_GettingStartedBuild.png
  docs_src/getting-started/EdgeX_GettingStartedClone.png
  docs_src/getting-started/EdgeX_GettingStartedRun.png
  docs_src/getting-started/gcc-logo.png
  docs_src/getting-started/golang-vector-6.png
  mkdocs.yml
Labels: documentation

#176 updated getting started for user guide
  docs_src/general/Definitions.md
  docs_src/getting-started/Ch-GettingStartedUsers.md
  docs_src/getting-started/EdgeX_GettingStartedReleaseFolders.png
  docs_src/getting-started/EdgeX_GettingStartedUsrActiveContainers.png
  docs_src/getting-started/EdgeX_GettingStartedUsrConsul.png
  docs_src/getting-started/EdgeX_GettingStartedUsrDocker.png
  docs_src/getting-started/EdgeX_GettingStartedUsrDockerComposeConfig.png
  docs_src/getting-started/EdgeX_GettingStartedUsrDockerComposePull.png
  docs_src/getting-started/EdgeX_GettingStartedUsrDownloadDockerCompose.png
  docs_src/getting-started/EdgeX_GettingStartedUsrExitedState.png
  docs_src/getting-started/EdgeX_GettingStartedUsrFileVolume.png
  docs_src/getting-started/EdgeX_GettingStartedUsrFormat.png
  docs_src/getting-started/EdgeX_GettingStartedUsrInstallDocker.png
  docs_src/getting-started/EdgeX_GettingStartedUsrLogs.png
  docs_src/getting-started/EdgeX_GettingStartedUsrNoContainers.png
  docs_src/getting-started/EdgeX_GettingStartedUsrPing.png
  docs_src/getting-started/EdgeX_GettingStartedUsrRunEdgex.png
  docs_src/getting-started/EdgeX_GettingStartedUsrStart.png
  docs_src/getting-started/EdgeX_GettingStartedUsrStartIndividual.png
  docs_src/getting-started/EdgeX_GettingStartedUsrState.png
  docs_src/getting-started/EdgeX_GettingStartedUsrStop.png
  docs_src/getting-started/EdgeX_GettingStartedUsrStopIndividual.png
  docs_src/getting-started/EdgeX_GettingStartedUsrStopRemove.png
  docs_src/getting-started/EdgeX_GettingStartedUsrtartIndividual.png
  docs_src/getting-started/quick-start/index.md
Labels: documentation

#188 Update docker-compose references to release Geneva
  docs_src/examples/Ch-ExamplesAddingMQTTDevice.md
  docs_src/examples/Ch-ExamplesAddingModbusDevice.md
  docs_src/microservices/security/Ch-SecretStore.md
  docs_src/walk-through/Ch-WalkthroughRunning.md
Labels: 3-high, documentation, geneva

#185 updated and cleaned up working with hybrid dev page for Geneva
  docs_src/getting-started/Ch-GettingStartedHybrid.md
  docs_src/getting-started/EdgeX_GettingStartedDevMongoCommands.png
  docs_src/getting-started/EdgeX_GettingStartedDevMongoRun.png
  docs_src/getting-started/EdgeX_GettingStartedDevMongoStart.png
  docs_src/getting-started/EdgeX_GettingStartedHybridBuild.png
  docs_src/getting-started/EdgeX_GettingStartedHybridRun.png
Labels: documentation, geneva

#181 doc: Add section Configure ADD_PROXY_ROUTE of API Gateway
  docs_src/microservices/security/Ch-APIGateway.md
Labels: 2-medium, app-services, documentation, geneva, security-services

#203 fixes #143 and #148; cleaned up rules pages; added Kuiper example pag…
  docs_src/examples/Ch-CommandingDeviceThroughRulesEngine.md
  docs_src/microservices/support/Kuiper/Ch-Kuiper.md
  docs_src/microservices/support/Kuiper/EdgeX_KuiperRulesEngine.png
  mkdocs.yml
Labels: documentation, geneva
