Repository edgexfoundry/edgex-docs, pull requests merged in 2021-09, with the labels that each got.

#561 feat: updated API walthrough tutorial to V2
  docs_src/walk-through/Ch-Walkthrough.md
  docs_src/walk-through/Ch-WalkthroughCommands.md
  docs_src/walk-through/Ch-WalkthroughData.md
  docs_src/walk-through/Ch-WalkthroughDeviceProfile.md
  docs_src/walk-through/Ch-WalkthroughDeviceService.md
  docs_src/walk-through/Ch-WalkthroughExporting.md
  docs_src/walk-through/Ch-WalkthroughProvision.md
  docs_src/walk-through/Ch-WalkthroughReading.md
  docs_src/walk-through/Ch-WalkthroughUseCase.md
  docs_src/walk-through/EdgeX_CameraMonitorProfile.yml
  docs_src/walk-through/EdgeX_WalkthroughAppServiceLog.png
  docs_src/walk-through/EdgeX_WalkthroughConsulKeyValue.png
  docs_src/walk-through/EdgeX_WalkthroughConsulSetLogLevel.png
  docs_src/walk-through/EdgeX_WalkthroughCurlPOST_Response.png
  docs_src/walk-through/EdgeX_WalkthroughGetCommands.png
  docs_src/walk-through/EdgeX_WalkthroughGetCommands_Curl.png
  docs_src/walk-through/EdgeX_WalkthroughPostmanFile.png
  docs_src/walk-through/EdgeX_WalkthroughPostmanHeaders.png
  docs_src/walk-through/EdgeX_WalkthroughPostmanPOST_Response.png
  docs_src/walk-through/EdgeX_WalkthroughPutCommandURL.png
  docs_src/walk-through/EdgeX_WalkthroughSendEvent.png
  docs_src/walk-through/EdgeX_WalkthroughSendEvent_Curl.png
  mkdocs.yml
Labels: documentation, ireland

#583 feat: update the SNMP device service example to V2
  docs_src/examples/Ch-ExamplesAddingSNMPDevice.md
  docs_src/examples/EdgeX_ExamplesMoxaIO.JPG
  docs_src/examples/EdgeX_Examples_Patlite.jpg
  docs_src/examples/EdgeX_Patlite_Green_On.jpg
  docs_src/examples/docker-compose.yml
  docs_src/examples/patlite-snmp.yml
Labels: documentation, ireland

#585 fix: dependency installation for C development
  docs_src/getting-started/Ch-GettingStartedCDevelopers.md
Labels: 3-high, device-services, dependencies, ireland

#591 feat: Document the the Kong worker process setting
  docs_src/security/Ch-APIGateway.md
Labels: hold, jakarta

#592 fix: Document the MaxResultCount default value to be new value used
  docs_src/microservices/configuration/CommonConfiguration.md
Labels: jakarta

#576 feat: change error message in API Walkthrough example on calling comm…
  docs_src/walk-through/Ch-WalkthroughCommands.md
Labels: documentation, jakarta

#566 feat: update MQTT Examples for Jakarta, document useTopicLevels capability
  docs_src/examples/Ch-ExamplesAddingMQTTDevice.md
Labels: jakarta

#551 feat: Add Pipeline Per Topic documentation
  docs_src/microservices/application/AdvancedTopics.md
  docs_src/microservices/application/AppFunctionContextAPI.md
  docs_src/microservices/application/AppServiceConfigurable.md
  docs_src/microservices/application/ApplicationServiceAPI.md
Labels: hold, jakarta

#587 feat: Document new Seeding Service Secrets capability
  docs_src/microservices/configuration/CommonConfiguration.md
  docs_src/security/SeedingServiceSecrets.md
  mkdocs.yml
Labels: hold, jakarta
