Repository edgexfoundry/edgex-docs, pull requests merged in 2021-06, with the labels that each got.

#405 feat(security): Add documentation about add-on service section
  docs_src/security/Ch-Configuring-Add-On-Services.md
  docs_src/security/Ch-Secure-MessageBus.md
  mkdocs.yml
Labels: 2-medium, documentation, ireland

#421 feat(security): Add documentation section for securing Consul
  docs_src/security/Ch-Secure-Consul.md
  docs_src/security/consul-login-input.png
  docs_src/security/consul-login.png
  mkdocs.yml
Labels: 2-medium, documentation

#393 fix: Batch security documentation updates for Ireland
  docs_src/security/Ch-APIGateway.md
  docs_src/security/Ch-AccessEdgeXRESTResources.md
  docs_src/security/Ch-SecretStore.md
  docs_src/security/Ch-SecurityIssues.md
  docs_src/security/Ch-StartingSecurity.md
  docs_src/security/EdgeX-UI-Consul-01.png
  docs_src/security/EdgeX-UI-Consul-02.png
  docs_src/security/EdgeX-UI-Consul-03.png
  docs_src/security/EdgeX-UI-Consul-04.png
  docs_src/security/EdgeX-UI-Consul-05.png
  docs_src/security/EdgeX-UI-Consul-06.png
  docs_src/security/EdgeX-UI-Consul-07.png
  docs_src/security/EdgeX-UI-Consul-08.png
  docs_src/security/EdgeX-UI-Consul-09.png
  docs_src/security/Running.Security.png
  docs_src/security/secrets-config-proxy.md
  docs_src/security/secrets-config.md
  docs_src/security/security-secrets-setup.1.md
  mkdocs.yml
Labels: documentation, ireland
