Repository edgexfoundry/edgex-docs, pull requests merged in 2022-05, with the labels that each got.

#761 ci: Update all links to examples repo to use v2.2.0 tag
  docs_src/examples/AppServiceExamples.md
  docs_src/examples/index.md
  docs_src/getting-started/ApplicationFunctionsSDK.md
  docs_src/microservices/application/Triggers.md
  docs_src/security/Ch-RemoteDeviceServices.md
Labels: documentation

#762 ci: automated version file changes for [2.3]
  docs/index.html
  docs/versions.json
Labels: documentation, ci

#763 ci: automated Swagger API version changes: 2.2.0 --> 2.3.0
  docs_src/api/applications/Ch-APIAppFunctionsSDK.md
  docs_src/api/core/Ch-APICoreCommand.md
  docs_src/api/core/Ch-APICoreData.md
  docs_src/api/core/Ch-APICoreMetadata.md
  docs_src/api/devices/Ch-APIDeviceSDK.md
  docs_src/api/management/Ch-APISystemManagement.md
  docs_src/api/support/Ch-APISupportNotifications.md
  docs_src/api/support/Ch-APISupportScheduler.md
Labels: documentation, ci

#766 fix: Fix typos in Default Service Ports from previous PR (Levski)
  docs_src/general/ServicePorts.md
Labels: documentation

#768 feat: Add notes to metrics sections that it is Beta released [Kamakura]
  docs_src/microservices/application/AdvancedTopics.md
  docs_src/microservices/application/AppServiceConfigurable.md
  docs_src/microservices/application/BuiltIn.md
  docs_src/microservices/general/index.md
Labels: documentation

#769 build: Publish to 2.3 version
  mkdocs.yml
Labels: documentation

#767 fix: Fix typos in Default Service Ports from previous PR (kamakura)
  docs_src/general/ServicePorts.md
Labels: documentation

#764 Add native build run
  docs_src/getting-started/native/BuildAppServiceConf.png
  docs_src/getting-started/native/BuildDeviceVirtual.png
  docs_src/getting-started/native/BuildEdgeXGoServices.png
  docs_src/getting-started/native/BuildEssentialCheck.png
  docs_src/getting-started/native/BuildGUI.png
  docs_src/getting-started/native/BuildeKuiper.png
  docs_src/getting-started/native/Ch-BuildRunNative.md
  docs_src/getting-started/native/Ch-BuildRunOnLinuxDistro.md
  docs_src/getting-started/native/CheckeKuiperRunning-OK.png
  docs_src/getting-started/native/CheckeKuiperRunning-Oops.png
  docs_src/getting-started/native/ConsulCheck.png
  docs_src/getting-started/native/CoreSupportingServicesRunning.png
  docs_src/getting-started/native/CreateeKuiperRule.png
  docs_src/getting-started/native/CreateeKuiperStream.png
  docs_src/getting-started/native/DataCenterDisplayData.png
  docs_src/getting-started/native/GitCheck.png
  docs_src/getting-started/native/GoLangCheck.png
  docs_src/getting-started/native/LocationConfigAppService.png
  docs_src/getting-started/native/LocationDeviceVirtualService.png
  docs_src/getting-started/native/LocationEdgeXGUI.png
  docs_src/getting-started/native/LocationeKuiper.png
  docs_src/getting-started/native/LocationeKuiperStreamLog.png
  docs_src/getting-started/native/NohupTailFile.png
  docs_src/getting-started/native/RedisCheck.png
  docs_src/getting-started/native/RunConsulUI.png
  docs_src/getting-started/native/RunGUI.png
  docs_src/getting-started/native/StreamOfEventReadings.png
  docs_src/getting-started/native/TaileKuiperLog.png
  docs_src/getting-started/native/ZeroMQCheck.png
  mkdocs.yml
Labels: documentation, kamakura
