Repository edgexfoundry/edgex-docs, pull requests merged in 2022-10, with the labels that each got.

#812 feat: address EdgeX and Cloud Native computing
  docs_src/general/CN-EN.png
  docs_src/general/CNCF-logo.png
  docs_src/general/EdgeX_CN.md
  mkdocs.yml
Labels: 1-low, levski

#873 feat: Add Device Service custom metrics section
  docs_src/getting-started/Ch-GettingStartedSDK-Go.md
  docs_src/microservices/application/AdvancedTopics.md
  docs_src/microservices/configuration/CommonConfiguration.md
  docs_src/microservices/device/sdk/SDK-Go-API.md
  docs_src/microservices/general/index.md
Labels: documentation

#863 feat: Create Record and Replay ADR
  docs_src/design/TOC.md
  docs_src/design/adr/application/0025-Record-and-Replay.md
Labels: ADR

#877 feat: Document new common service metrics
  docs_src/microservices/configuration/CommonConfiguration.md
  docs_src/microservices/core/data/Ch-CoreData.md
  docs_src/microservices/core/metadata/Ch-Metadata.md
  docs_src/microservices/general/index.md
  docs_src/microservices/support/notifications/Ch-AlertsNotifications.md
  docs_src/microservices/support/scheduler/Ch-Scheduler.md
Labels: documentation

#880 feat: Document new "none" value for EDGEX_CONFIGURATION_PROVIDER
  docs_src/microservices/configuration/CommonEnvironmentVariables.md
Labels: documentation

#881 feat: Document Device Service EventsSent and ReadingsSent metrics
  docs_src/getting-started/Ch-GettingStartedSDK-Go.md
  docs_src/microservices/application/GeneralAppServiceConfig.md
  docs_src/microservices/configuration/CommonConfiguration.md
  docs_src/microservices/device/Ch-DeviceServices.md
Labels: documentation
