Repository edgexfoundry/edgex-docs, pull requests merged in 2022-08, with the labels that each got.

#822 ci: revert google analytics config change for geneva
  mkdocs.yml
Labels: ci

#786 feat: add build and run on ARM32
  docs_src/getting-started/native/Ch-BuildRunNative.md
  docs_src/getting-started/native/Ch-BuildRunOnArm32.md
  docs_src/getting-started/native/LocationeKuiper-arm.png
  docs_src/getting-started/native/LocationeKuiperStreamLog-arm.png
  docs_src/getting-started/native/TaileKuiperLog-arm.png
  docs_src/getting-started/native/ZeroMQCheck-arm.png
  mkdocs.yml
Labels: documentation, levski

#844 docs: add management token
  docs_src/security/Ch-Secure-Consul.md
Labels: documentation, 1-low
