Repository edgexfoundry/edgex-docs, pull requests merged in 2022-07, with the labels that each got.

#783 ci: enable htmlproofer
  docs_src/examples/index.md
  docs_src/microservices/support/eKuiper/Ch-eKuiper.md
  mkdocs.yml
Labels: documentation, ci

#799 feat: docs for built-in pipeline function to wrap event
  docs_src/microservices/application/AppServiceConfigurable.md
  docs_src/microservices/application/BuiltIn.md
Labels: documentation

#802 feat: Document API for Device SDK Go
  docs_src/microservices/device/sdk/SDK-Go-API.md
  mkdocs.yml
Labels: documentation, 2-medium, device-services

#804 ci: enable mkdoc macros
  Dockerfile.docs
  docs_src/api/applications/Ch-APIAppFunctionsSDK.md
  docs_src/api/core/Ch-APICoreCommand.md
  docs_src/api/core/Ch-APICoreData.md
  docs_src/api/core/Ch-APICoreMetadata.md
  docs_src/api/devices/Ch-APIDeviceSDK.md
  docs_src/api/management/Ch-APISystemManagement.md
  docs_src/api/support/Ch-APISupportNotifications.md
  docs_src/api/support/Ch-APISupportScheduler.md
  docs_src/examples/AppServiceExamples.md
  docs_src/examples/index.md
  docs_src/getting-started/ApplicationFunctionsSDK.md
  docs_src/microservices/application/Triggers.md
  docs_src/security/Ch-RemoteDeviceServices.md
  docs_src/security/secrets-config-proxy.md
  mkdocs.yml
  template_macros.yaml
Labels: ci

#807 ci: add retry to mkdocs build stage
  Jenkinsfile
Labels: ci

#805 feat(microservices): Add NATS MessageBus Overview for App Service Trigger
  docs_src/microservices/application/Triggers.md
Labels: documentation, 3-high

#810 doc: updated the SDK-Go-API.md document to reflect the new functions …
  docs_src/microservices/device/sdk/SDK-Go-API.md
Labels: documentation, enhancement
