Repository edgexfoundry/edgex-docs, pull requests merged in 2022-04, with the labels that each got.

#734 fix: correct the env var reference in app service configurable docume…
  docs_src/microservices/application/AppServiceConfigurable.md
Labels: bug, documentation, kamakura

#725 fix(walkthru): walkthrough json body example fix
  docs_src/walk-through/Ch-WalkthroughDeviceService.md
Labels: bug, documentation, kamakura

#739 feat: Document new Custom Application Service Metrics capability
  docs_src/microservices/application/AdvancedTopics.md
  docs_src/microservices/application/AppFunctionContextAPI.md
  docs_src/microservices/application/ApplicationServiceAPI.md
  docs_src/microservices/application/GeneralAppServiceConfig.md
  docs_src/microservices/general/index.md
Labels: documentation, enhancement

#743 ci: update to ubuntu based agent
  Jenkinsfile
Labels: ci

#656 feat(adr): addition of north-south messaging ADR
  docs_src/design/TOC.md
  docs_src/design/adr/0023-North-South-Messaging.md
  docs_src/design/adr/command-message-bridge.png
  docs_src/design/adr/command-msg-structure.png
  docs_src/design/adr/command-msg.png
  docs_src/design/adr/command-service-topics.png
Labels: documentation, ADR, kamakura

#744 feat: address supported architectures in Getting Started
  docs_src/getting-started/index.md
Labels: documentation, kamakura
