Repository edgexfoundry/edgex-docs, pull requests merged in 2023-01, with the labels that each got.

#918 fix: add robots.txt in order to have search engines use latest docs
  docs_src/robots.txt
Labels: documentation

#921 refactor: Update Minnesota version of docs to be 3.0
  docs/versions.json
  mkdocs.yml
  template_macros.yaml
Labels: documentation

#936 fix: move robots.txt to the docs folder
  docs/robots.txt
Labels: ci

#941 fix: add sitemap to robots.txt to allow for Google rescan
  docs/robots.txt
Labels: bug, documentation

#947 fix: remove deprecated PushToCore references
  docs_src/microservices/application/AppFunctionContextAPI.md
  docs_src/microservices/application/AppServiceConfigurable.md
  docs_src/microservices/application/BuiltIn.md
Labels: documentation
